### ISSUE TITLE
Plugin should not require MySQL SUPER privileges to execute

### ISSUE THREAD

**Issue by RedSpid3r** [mantisbt-plugins/GaugeSupport#10]
Using the updated version of the plugin gives me the following error when trying to view the issue ranking page:

> APPLICATION ERROR #401
> 
> Database query failed. Error received from database was #1227: Access denied; you need (at least one of) the SUPER privilege(s) for this operation for the query: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')).
> Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

**Comment by ghost** [comment]
Can you check if the database user has full rights on the database? In order to execute apparanetly it requires Super privileges. I am in the process (slowly) of rewriting in order to avoid these errors and to make it fully compliant.

**Comment by stigzler** [comment]
Same issue here - not really sure many of us will be willing to grant SU permissions on this given what it could open databases up to. Look forward to a fixed release...

**Comment by Skyedra** [comment]
+1 - Requiring super privileges on a database is a ridiculous (and frankly, suspicious) implementation decision

**Comment by dregad** [comment]
The SUPER privileges are required to set *sql_mode* (to clear ONLY_FULL_GROUP_BY mode).

This mode rejects queries where non-aggregated columns are expected, and is enabled by default in MySQL 5.7 and later.

The SQL query retrieving the data in the Rankings page needs to be updated so it can be executed in ONLY_FULL_GROUP_BY mode. This requires declaring all unique columns in the GROUP BY clause.
