### ISSUE TITLE
Tables/footer get broken

### ISSUE THREAD

**Issue by Skyedra** [mantisbt-plugins/GaugeSupport#11]
With plugin enabled on Mantis 2.21.1, the tables get a little broken.  Not sure if that's how the plugin table is supposed to look (with a lot of space for strong support), but it's definitely changing width of issue history table, and the footer is off-screen.

![image](https://user-images.githubusercontent.com/22365940/62583038-68bcfd80-b863-11e9-936b-9af48d5cf13d.png)

**Comment by dregad** [comment]
This is most likely caused by malformed HTML (maybe a missing `</div>` tag).
