### ISSUE TITLE
Not working on 2.x

### ISSUE THREAD

**Issue by RedSpid3r** [mantisbt-plugins/GaugeSupport#2]
Installed the plugin but when you click the "Issue Support Ranking" link i get the following error:

> APPLICATION ERROR #401
> 
> Database query failed. Error received from database was #1146: Table '********.mantis_plugin_GaugeSupport_support_data_table' doesn't exist for the query: SELECT
> max(sd.bugid) as bugid,
> count(sd.rating) as no_of_ratings,
> sum(sd.rating) as sum_of_ratings,
> avg(sd.rating) as avg_rating,
> max(sd.rating) as highest_rating,
> min(sd.rating) as lowest_rating,
> IFNULL(bm2_count,0) AS bm2_count,
> IFNULL(bm2_sum,0) AS bm2_sum,
> IFNULL(bm1_count,0) AS bm1_count,
> IFNULL(bm1_sum,0) AS bm1_sum,
> IFNULL(b2_count,0) AS b2_count,
> IFNULL(b2_sum,0) AS b2_sum,
> IFNULL(b1_count,0) AS b1_count,
> IFNULL(b1_sum,0) AS b1_sum
> FROM mantis_plugin_GaugeSupport_support_data_table sd
> INNER JOIN mantis_bug_table b ON sd.bugid = b.id
> LEFT OUTER JOIN (SELECT bugid, count(rating) as bm2_count, sum(rating) as bm2_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = -2) bm2 ON sd.bugid = bm2.bugid
> LEFT OUTER JOIN (SELECT bugid, count(rating) as bm1_count, sum(rating) as bm1_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = -1) bm1 ON sd.bugid = bm1.bugid
> LEFT OUTER JOIN (SELECT bugid, count(rating) as b2_count, sum(rating) as b2_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = 2) b2 ON sd.bugid = b2.bugid
> LEFT OUTER JOIN (SELECT bugid, count(rating) as b1_count, sum(rating) as b1_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = 1) b1 ON sd.bugid = b1.bugid
> WHERE b.project_id = 7 AND b.resolution NOT IN (20,50,60,70,91) AND b.status NOT IN (80,90)
> GROUP BY sd.bugid
> ORDER BY sum(sd.rating) DESC .
> Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.

also there are no voting buttons/options on the view issue page

**Comment by ghost** [comment]
Have not tested it yet on 2.5.1 but will test it on a fresh new install of the latest version 2.10.
Did it fail on a vanilla installation on your end or did it fail on an existing installation with (many) other plugins?
In addition, can you provide information on PHP/SQL & OS version in use?

Op ma, 01/08/2018 05:35 PM, RedSpid3r <notifications@github.com> schreef:
> 
Installed the plugin but when you click the "Issue Support Ranking" link i get the following error:
`APPLICATION ERROR #401
Database query failed. Error received from database was #1054: Unknown column 'rating' in 'field list' for the query: SELECT
> 
max(sd.bugid) as bugid,
> 
count(sd.rating) as no_of_ratings,
> 
sum(sd.rating) as sum_of_ratings,
> 
avg(sd.rating) as avg_rating,
> 
max(sd.rating) as highest_rating,
> 
min(sd.rating) as lowest_rating,
> 
IFNULL(bm2_count,0) AS bm2_count,
> 
IFNULL(bm2_sum,0) AS bm2_sum,
> 
IFNULL(bm1_count,0) AS bm1_count,
> 
IFNULL(bm1_sum,0) AS bm1_sum,
> 
IFNULL(b2_count,0) AS b2_count,
> 
IFNULL(b2_sum,0) AS b2_sum,
> 
IFNULL(b1_count,0) AS b1_count,
> 
IFNULL(b1_sum,0) AS b1_sum
> 
FROM mantis_plugin_GaugeSupport_support_data_table sd
> 
INNER JOIN mantis_bug_table b ON sd.bugid = b.id
> 
LEFT OUTER JOIN (SELECT bugid, count(rating) as bm2_count, sum(rating) as bm2_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = -2) bm2 ON sd.bugid = bm2.bugid
> 
LEFT OUTER JOIN (SELECT bugid, count(rating) as bm1_count, sum(rating) as bm1_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = -1) bm1 ON sd.bugid = bm1.bugid
> 
LEFT OUTER JOIN (SELECT bugid, count(rating) as b2_count, sum(rating) as b2_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = 2) b2 ON sd.bugid = b2.bugid
> 
LEFT OUTER JOIN (SELECT bugid, count(rating) as b1_count, sum(rating) as b1_sum FROM mantis_plugin_GaugeSupport_support_data_table GROUP BY bugid, rating HAVING rating = 1) b1 ON sd.bugid = b1.bugid
> 
WHERE b.project_id = 7 AND b.resolution NOT IN (20,50,60,70,91) AND b.status NOT IN (80,90)
> 
GROUP BY sd.bugid
> 
ORDER BY sum(sd.rating) DESC .
> 
Please use the "Back" button in your web browser to return to the previous page. There you can correct whatever problems were identified in this error or select another action. You can also click an option from the menu bar to go directly to a new section.`
also there are no voting buttons/options on the view issue page
—
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.




  
 *

**Comment by RedSpid3r** [comment]
Plugin installed without any errors via the Manage Plugin screen.

Using Mantis 2.5.1 on 

> Apache Version | 2.4.23
> PHP Version | 5.6.29
> MySQL Version | 10.0.33-MariaDB

**EDIT:**
Updated to 2.10.0 issue still persists

**Comment by ghost** [comment]
​​Just checked with a clean install of Mantis 2.10.
Installation went withour errors, DB table nicely installed, no problem with the menu option.
Voting buttons become visible depending on which inclusions/exclusion you have defined within the config of the plugin.
Exclude nothing and include all to start with and the section pops just after the Notes section.

Op di, 01/09/2018 08:50 PM, RedSpid3r <notifications@github.com> schreef:

Op di, 01/09/2018 08:50 PM, RedSpid3r <notifications@github.com> schreef:
> 
Plugin installed without any errors via the Manage Plugin screen.
Using Mantis 2.5.1 on

> 

Apache Version | 2.4.23
> 
PHP Version | 5.6.29
> 
MySQL Version | 10.0.33-MariaDB
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




  
 *

**Comment by RedSpid3r** [comment]
Deleted GaugeSupport folder from /public_html/plugins, downloaded ZIP and re-uploaded. Clicked install via Manage Plugins page in Mantis - no errors but same error message when clicking "Issue Support Ranking" and no voting buttons appear.

**Comment by ghost** [comment]
​just another question, did you post this by any chance:
http://www.spyderlovers.com/forums/showthread.php?110010-FREE-FREE

Op wo, 01/10/2018 07:57 PM, RedSpid3r <notifications@github.com> schreef:
> 
Deleted GaugeSupport folder from /public_html/plugins, downloaded ZIP and re-uploaded. Clicked install via Manage Plugins page in Mantis - no errors but same error message when clicking "Issue Support Ranking" and no voting buttons appear.
—
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.




  
 *

**Comment by RedSpid3r** [comment]
Was there any update on this?

**Comment by ghost** [comment]
Yes there is a new version so all should be fine now

**Comment by dregad** [comment]
@CasN sorry but I don't see any new version, https://github.com/mantisbt-plugins/GaugeSupport/tree/master is still at version 2.0.2, commit 5fd657c on 17 Sep 2017 - maybe you forgot to push the changes here ?
