### ISSUE TITLE
Not working with PostgreSQL

### ISSUE THREAD

**Issue by eazrael** [mantisbt-plugins/GaugeSupport#4]
Clicking on the "Issue Support Ranking" Button just gives an error page: 
#-2: ERROR: syntax error at or near "sql_mode"
LINE 1: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GR...
^ für die Abfrage: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')).

**Comment by ghost** [comment]
This indeed is a statement which needs to be adjusted to fit all supported databases. To be fixed

**Comment by eazrael** [comment]
I implemented postgres queries and added a readme.md which I guessed from the code:
https://github.com/eazrael/GaugeSupport
Would be happy if you pull the changes
