### ISSUE TITLE
severity is checked instead of resolution in issue_ranking.php

### ISSUE THREAD

**Issue by felsss** [mantisbt-plugins/GaugeSupport#6]
`	$current= explode(",", plugin_config_get( 'gaugesupport_excl_resolution' ));
	if(in_array(bug_get_field($bugid, 'severity'),$current)){
		return;
	}`

Shouldn't it be
`
$current= explode(",", plugin_config_get( 'gaugesupport_excl_resolution' ));
	if(in_array(bug_get_field($bugid, 'resolution'),$current)){
		return;
	}`

**Comment by ghost** [comment]
Yes, you are right. Will adjust this soonest.
