### ISSUE TITLE
There is a dot at the end of the link to the bug view in issue_ranking.php

### ISSUE THREAD

**Issue by felsss** [mantisbt-plugins/GaugeSupport#7]
Line 114 in issue_ranking.php:
`<td><a href="view.php?id=<?php echo $bug->id ?>."><?php echo $bug->id ?></td>`
Which makes Mantis complaining about a wrong bug ID when clicking the link.

Works better when removing the dot like below:
`<td><a href="view.php?id=<?php echo $bug->id ?>"><?php echo $bug->id ?></td>`

**Comment by ghost** [comment]
WEll spotted, will be adjusted soonest.

**Comment by okainov** [comment]
@CasN usually you keep issues unless they're resolved... Is there any reason you're closing it?
